services:
  - type: web
    name: commentanaly
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: SECRET_KEY
        generateValue: true
      - key: YOUTUBE_API_KEY
        sync: false
      - key: APIFY_API_TOKEN
        sync: false
      - key: RENDER
        value: true 
